# Data directories
train_dir: "data/train"  # Contains 'mogging' and 'not_mogging' subdirectories
val_dir: "data/val"      # Contains 'mogging' and 'not_mogging' subdirectories
checkpoint_dir: "checkpoints"

# Training parameters
batch_size: 32
num_workers: 4
learning_rate: 0.0001
max_epochs: 100
patience: 10  # for early stopping

# Model parameters
model_name: "facebook/convnext-base-224-22k"